version: '3.5'

services:
  postgres:
    container_name: pg
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Migration_db
      PGDATA: /data/postgres
    volumes:
       - ./db_data:/data/postgres
    ports:
      - "5432:5432"

    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

    restart: always


volumes:
    db_data:

networks:
  default:
    external:
      name: external-network
